import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export function generateInvoicePDF({
  items,
  subtotal,
  invoiceNumber,
  shopName,
  buyerName,
  date,
  gstRate,
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const gstAmount = parseFloat(((subtotal * gstRate) / 100).toFixed(2));
  const grandTotal = parseFloat((subtotal + gstAmount).toFixed(2));

  // Header
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, W, 38, "F");
  doc.setTextColor(232, 255, 71);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("BOL", 14, 17);
  doc.setTextColor(160, 160, 160);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("VOICE-POWERED INVOICE", 14, 24);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`INVOICE #${invoiceNumber}`, W - 14, 15, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(160, 160, 160);
  doc.text(date, W - 14, 22, { align: "right" });

  // From / To
  let y = 48;
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, y);
  doc.text("BILLED TO", W / 2, y);
  y += 5;
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.text(shopName || "My Shop", 14, y);
  doc.text(buyerName || "Customer", W / 2, y);

  // Divider
  y += 10;
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(14, y, W - 14, y);
  y += 6;

  // Table
  autoTable(doc, {
    startY: y,
    head: [["#", "Item", "Qty", "Unit", "Price (Rs.)", "Total (Rs.)"]],
    body: items.map((item, i) => [
      i + 1,
      item.name,
      item.qty,
      item.unit || "-",
      item.price.toFixed(2),
      item.total.toFixed(2),
    ]),
    headStyles: {
      fillColor: [10, 10, 10],
      textColor: [232, 255, 71],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      2: { halign: "center" },
      3: { halign: "center" },
      4: { halign: "right" },
      5: { halign: "right", fontStyle: "bold" },
    },
    margin: { left: 14, right: 14 },
  });

  // Totals block
  const ty = doc.lastAutoTable.finalY + 8;
  const bx = W - 78;
  const bw = 64;

  doc.setFillColor(248, 248, 248);
  doc.roundedRect(bx, ty, bw, gstRate > 0 ? 30 : 16, 2, 2, "F");

  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text("Subtotal", bx + 4, ty + 7);
  doc.setTextColor(20, 20, 20);
  doc.text(`Rs.${subtotal.toFixed(2)}`, bx + bw - 4, ty + 7, {
    align: "right",
  });

  if (gstRate > 0) {
    doc.setTextColor(80, 80, 80);
    doc.text(`GST (${gstRate}%)`, bx + 4, ty + 15);
    doc.setTextColor(20, 20, 20);
    doc.text(`Rs.${gstAmount.toFixed(2)}`, bx + bw - 4, ty + 15, {
      align: "right",
    });

    doc.setDrawColor(200, 200, 200);
    doc.line(bx + 4, ty + 19, bx + bw - 4, ty + 19);

    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(10, 10, 10);
    doc.text("TOTAL", bx + 4, ty + 27);
    doc.text(`Rs.${grandTotal.toFixed(2)}`, bx + bw - 4, ty + 27, {
      align: "right",
    });
  } else {
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(10, 10, 10);
    doc.text("TOTAL", bx + 4, ty + 12);
    doc.text(`Rs.${subtotal.toFixed(2)}`, bx + bw - 4, ty + 12, {
      align: "right",
    });
  }

  // Footer
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 280, W, 17, "F");
  doc.setTextColor(100, 100, 100);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Generated by BOL - Voice-Powered Invoice", 14, 290);
  doc.setTextColor(232, 255, 71);
  doc.text("Thank you for your business!", W - 14, 290, { align: "right" });

  doc.save(`BOL-Invoice-${invoiceNumber}.pdf`);
}

// Add this NEW function at the bottom — keep the existing generateInvoicePDF
export function generateInvoiceBlob({
  items,
  subtotal,
  invoiceNumber,
  shopName,
  buyerName,
  date,
  gstRate,
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = 210;
  const gstAmount = parseFloat(((subtotal * gstRate) / 100).toFixed(2));
  const grandTotal = parseFloat((subtotal + gstAmount).toFixed(2));

  // Header
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, W, 38, "F");
  doc.setTextColor(232, 255, 71);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(22);
  doc.text("BOL", 14, 17);
  doc.setTextColor(160, 160, 160);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("VOICE-POWERED INVOICE", 14, 24);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text(`INVOICE #${invoiceNumber}`, W - 14, 15, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(160, 160, 160);
  doc.text(date, W - 14, 22, { align: "right" });

  // From / To
  let y = 48;
  doc.setFontSize(8);
  doc.setTextColor(130, 130, 130);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, y);
  doc.text("BILLED TO", W / 2, y);
  y += 5;
  doc.setFontSize(12);
  doc.setTextColor(20, 20, 20);
  doc.setFont("helvetica", "bold");
  doc.text(shopName || "My Shop", 14, y);
  doc.text(buyerName || "Customer", W / 2, y);

  // Divider
  y += 10;
  doc.setDrawColor(220, 220, 220);
  doc.setLineWidth(0.3);
  doc.line(14, y, W - 14, y);
  y += 6;

  // Table
  autoTable(doc, {
    startY: y,
    head: [["#", "Item", "Qty", "Unit", "Price (Rs.)", "Total (Rs.)"]],
    body: items.map((item, i) => [
      i + 1,
      item.name,
      item.qty,
      item.unit || "-",
      item.price.toFixed(2),
      item.total.toFixed(2),
    ]),
    headStyles: {
      fillColor: [10, 10, 10],
      textColor: [232, 255, 71],
      fontStyle: "bold",
      fontSize: 9,
    },
    bodyStyles: { fontSize: 9, textColor: [30, 30, 30] },
    alternateRowStyles: { fillColor: [248, 248, 248] },
    columnStyles: {
      0: { cellWidth: 10, halign: "center" },
      2: { halign: "center" },
      3: { halign: "center" },
      4: { halign: "right" },
      5: { halign: "right", fontStyle: "bold" },
    },
    margin: { left: 14, right: 14 },
  });

  // Totals block
  const ty = doc.lastAutoTable.finalY + 8;
  const bx = W - 78;
  const bw = 64;

  // Calculate box height based on content
  const boxHeight = gstRate > 0 ? 40 : 16;

  doc.setFillColor(248, 248, 248);
  doc.roundedRect(bx, ty, bw, boxHeight, 2, 2, "F");

  // Subtotal
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(80, 80, 80);
  doc.text("Subtotal", bx + 4, ty + 7);
  doc.setTextColor(20, 20, 20);
  doc.text(`Rs.${subtotal.toFixed(2)}`, bx + bw - 4, ty + 7, {
    align: "right",
  });

  if (gstRate > 0) {
    const cgst = parseFloat((gstAmount / 2).toFixed(2));
    const sgst = parseFloat((gstAmount / 2).toFixed(2));

    // CGST
    doc.setTextColor(80, 80, 80);
    doc.text(`CGST (${gstRate / 2}%)`, bx + 4, ty + 15);
    doc.setTextColor(20, 20, 20);
    doc.text(`Rs.${cgst.toFixed(2)}`, bx + bw - 4, ty + 15, { align: "right" });

    // SGST
    doc.setTextColor(80, 80, 80);
    doc.text(`SGST (${gstRate / 2}%)`, bx + 4, ty + 22);
    doc.setTextColor(20, 20, 20);
    doc.text(`Rs.${sgst.toFixed(2)}`, bx + bw - 4, ty + 22, { align: "right" });

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(bx + 4, ty + 26, bx + bw - 4, ty + 26);

    // Total
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(10, 10, 10);
    doc.text("TOTAL", bx + 4, ty + 34);
    doc.text(`Rs.${grandTotal.toFixed(2)}`, bx + bw - 4, ty + 34, {
      align: "right",
    });
  } else {
    // No GST — just show total
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(10, 10, 10);
    doc.text("TOTAL", bx + 4, ty + 12);
    doc.text(`Rs.${subtotal.toFixed(2)}`, bx + bw - 4, ty + 12, {
      align: "right",
    });
  }

  // Footer
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 280, W, 17, "F");
  doc.setTextColor(100, 100, 100);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text("Generated by BOL - Voice-Powered Invoice", 14, 290);
  doc.setTextColor(232, 255, 71);
  doc.text("Thank you for your business!", W - 14, 290, { align: "right" });

  // Return as blob instead of downloading
  return doc.output("blob");
}
